spring:
  profiles:
    default: local

  application:
    name: guesthouse

oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI}


jwt:
  token:
    secret-key:
    access-expiration-time:
    refresh-expiration-time:
